export const restaurants = [
  {
    id: 1,
    imageUrl: 'p1.avif',
    offer: '₹600 for two',
    restaurantName: 'Sangeetha Veg Restaurant',
    rating: '4.6',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '40-45 mins',
    food: 'South Indian, North Indian, Chinese',
    location: 'Urapakkam',
    pureVeg: true,
    priceRange: '₹300-₹600',
    newOnSwiggy: true  
  },
  {
    id: 2,
    imageUrl: 'p2.avif',
    offer: '₹100 OFF ABOVE ₹399',
    restaurantName: 'Sree Gupta Bhavan',
    rating: '4.6',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '35-40 mins',
    food: 'Sweets, Chaat',
    location: 'Sri Nagar',
    pureVeg: true,
    priceRange: '₹200-₹400',
    newOnSwiggy: false
  },
  {
    id: 3,
    imageUrl: 'p3.avif',
    offer: '',
    restaurantName: 'A2B - Adyar Ananda Bhavan',
    rating: '4.4',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '45-50 mins',
    food: 'South Indian, Sweets, Chinese',
    location: 'Padur',
    pureVeg: true,
    priceRange: '₹300-₹700',
    newOnSwiggy: true  
  },
  {
    id: 4,
    imageUrl: 'p4.avif',
    offer: '',
    restaurantName: 'Sri Krishna Bhavan',
    rating: '4.5',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '35-40 mins',
    food: 'South Indian, Indian, Chinese, Juices',
    location: 'Padur',
    pureVeg: false,
    priceRange: '₹250-₹500',
    newOnSwiggy: false 
  },
  {
    id: 5,
    imageUrl: 'p5.avif',
    offer: '',
    restaurantName: 'Geetham Veg Restaurant',
    rating: '4.5',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '60-65 mins',
    food: 'South Indian, North Indian, Tandoor, Chinese, Chaat, Ice Cream',
    location: 'Medavakkam',
    pureVeg: true,
    priceRange: '₹400-₹800',
    newOnSwiggy: true  
  },
  {
    id: 6,
    imageUrl: 'p6.avif',
    offer: '',
    restaurantName: 'Shri Balaajee Bhavan',
    rating: '3.6',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '55-60 mins',
    food: 'North Indian, Chinese, South Indian, Tandoor',
    location: 'Chromepet',
    pureVeg: false,
    priceRange: '₹150-₹350',
    newOnSwiggy: false 
  },
  {
    id: 7,
    imageUrl: 'p7.avif',
    offer: '',
    restaurantName: 'Kumarakom',
    rating: '3.4',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '65-70 mins',
    food: 'Kerala, South Indian, Chinese',
    location: 'Pallikaranai',
    pureVeg: false,
    priceRange: '₹500-₹900',
    newOnSwiggy: true
  },
  {
    id: 8,
    imageUrl: 'p8.avif',
    offer: '',
    restaurantName: 'EatFit',
    rating: '3.3',
    noOfRatings: '(38k+ ratings)',
    deliveryTime: '60-65 mins',
    food: 'Chinese, Healthy Food, Tandoor, Pizzas, Thalis, Biryani',
    location: 'Postal Colony',
    pureVeg: true,
    priceRange: '₹350-₹750',
    newOnSwiggy: false 
  }
];
